/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import { useQuery } from '@tanstack/react-query'
import type {
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type { ArrayClub, GetListStageClubsParams } from '../../../domain/types/v1api'

import { orvalAxiosInstance } from '../../orval/orval-axios-instance'

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Get list
 */
export const getListStageClubs = (
  eventID: string,
  stageID: string,
  params?: GetListStageClubsParams,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal
) => {
  return orvalAxiosInstance<ArrayClub>(
    { url: `/api/v1/events/${eventID}/stages/${stageID}/clubs/`, method: 'GET', params, signal },
    options
  )
}

export const getGetListStageClubsQueryKey = (
  eventID: string,
  stageID: string,
  params?: GetListStageClubsParams
) => {
  return [
    `/api/v1/events/${eventID}/stages/${stageID}/clubs/`,
    ...(params ? [params] : [])
  ] as const
}

export const getGetListStageClubsQueryOptions = <
  TData = Awaited<ReturnType<typeof getListStageClubs>>,
  TError = unknown
>(
  eventID: string,
  stageID: string,
  params?: GetListStageClubsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListStageClubs>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetListStageClubsQueryKey(eventID, stageID, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getListStageClubs>>> = ({ signal }) =>
    getListStageClubs(eventID, stageID, params, requestOptions, signal)

  return { queryKey, queryFn, enabled: !!(eventID && stageID), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getListStageClubs>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetListStageClubsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getListStageClubs>>
>
export type GetListStageClubsQueryError = unknown

export function useGetListStageClubs<
  TData = Awaited<ReturnType<typeof getListStageClubs>>,
  TError = unknown
>(
  eventID: string,
  stageID: string,
  params?: GetListStageClubsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListStageClubs>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetListStageClubsQueryOptions(eventID, stageID, params, options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}

export const prefetchGetListStageClubsQuery = async <
  TData = Awaited<ReturnType<typeof getListStageClubs>>,
  TError = unknown
>(
  queryClient: QueryClient,
  eventID: string,
  stageID: string,
  params?: GetListStageClubsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListStageClubs>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
): Promise<QueryClient> => {
  const queryOptions = getGetListStageClubsQueryOptions(eventID, stageID, params, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}
