/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.3
 */
import { useQuery } from '@tanstack/react-query'
import type {
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type { ArrayStatsInClass } from '../../../domain/types/v1api'

import { orvalAxiosInstance } from '../../orval/orval-axios-instance'

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Get list
 */
export const getListStats = (
  eventID: string,
  stageID: string,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal
) => {
  return orvalAxiosInstance<ArrayStatsInClass>(
    { url: `/api/v1/events/${eventID}/stages/${stageID}/stats/`, method: 'GET', signal },
    options
  )
}

export const getGetListStatsQueryKey = (eventID: string, stageID: string) => {
  return [`/api/v1/events/${eventID}/stages/${stageID}/stats/`] as const
}

export const getGetListStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getListStats>>,
  TError = unknown
>(
  eventID: string,
  stageID: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListStats>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetListStatsQueryKey(eventID, stageID)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getListStats>>> = ({ signal }) =>
    getListStats(eventID, stageID, requestOptions, signal)

  return { queryKey, queryFn, enabled: !!(eventID && stageID), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getListStats>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetListStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getListStats>>>
export type GetListStatsQueryError = unknown

export function useGetListStats<TData = Awaited<ReturnType<typeof getListStats>>, TError = unknown>(
  eventID: string,
  stageID: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListStats>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetListStatsQueryOptions(eventID, stageID, options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}

export const prefetchGetListStatsQuery = async <
  TData = Awaited<ReturnType<typeof getListStats>>,
  TError = unknown
>(
  queryClient: QueryClient,
  eventID: string,
  stageID: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListStats>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
): Promise<QueryClient> => {
  const queryOptions = getGetListStatsQueryOptions(eventID, stageID, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}
