/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.4
 */
import { useMutation } from '@tanstack/react-query'
import type { MutationFunction, UseMutationOptions, UseMutationResult } from '@tanstack/react-query'

import type {
  PatchResetPasswordBody,
  PostListResetPasswordBody,
  ResUser
} from '../../../domain/types/v1api'

import { orvalAxiosInstance } from '../../orval/orval-axios-instance'

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Add new
 */
export const postListResetPassword = (
  postListResetPasswordBody: PostListResetPasswordBody,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal
) => {
  return orvalAxiosInstance<void>(
    {
      url: `/api/v1/resetPassword/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postListResetPasswordBody,
      signal
    },
    options
  )
}

export const getPostListResetPasswordMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postListResetPassword>>,
    TError,
    { data: PostListResetPasswordBody },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof postListResetPassword>>,
  TError,
  { data: PostListResetPasswordBody },
  TContext
> => {
  const mutationKey = ['postListResetPassword']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postListResetPassword>>,
    { data: PostListResetPasswordBody }
  > = (props) => {
    const { data } = props ?? {}

    return postListResetPassword(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostListResetPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof postListResetPassword>>
>
export type PostListResetPasswordMutationBody = PostListResetPasswordBody
export type PostListResetPasswordMutationError = unknown

export const usePostListResetPassword = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postListResetPassword>>,
    TError,
    { data: PostListResetPasswordBody },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationResult<
  Awaited<ReturnType<typeof postListResetPassword>>,
  TError,
  { data: PostListResetPasswordBody },
  TContext
> => {
  const mutationOptions = getPostListResetPasswordMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Edit
 */
export const patchResetPassword = (
  resetPasswordID: number,
  patchResetPasswordBody: PatchResetPasswordBody,
  options?: SecondParameter<typeof orvalAxiosInstance>
) => {
  return orvalAxiosInstance<ResUser>(
    {
      url: `/api/v1/resetPassword/${resetPasswordID}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: patchResetPasswordBody
    },
    options
  )
}

export const getPatchResetPasswordMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchResetPassword>>,
    TError,
    { resetPasswordID: number; data: PatchResetPasswordBody },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchResetPassword>>,
  TError,
  { resetPasswordID: number; data: PatchResetPasswordBody },
  TContext
> => {
  const mutationKey = ['patchResetPassword']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchResetPassword>>,
    { resetPasswordID: number; data: PatchResetPasswordBody }
  > = (props) => {
    const { resetPasswordID, data } = props ?? {}

    return patchResetPassword(resetPasswordID, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PatchResetPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchResetPassword>>
>
export type PatchResetPasswordMutationBody = PatchResetPasswordBody
export type PatchResetPasswordMutationError = unknown

export const usePatchResetPassword = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchResetPassword>>,
    TError,
    { resetPasswordID: number; data: PatchResetPasswordBody },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationResult<
  Awaited<ReturnType<typeof patchResetPassword>>,
  TError,
  { resetPasswordID: number; data: PatchResetPasswordBody },
  TContext
> => {
  const mutationOptions = getPatchResetPasswordMutationOptions(options)

  return useMutation(mutationOptions)
}
