/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.4
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type { ArraySimpleLog, ResRawUpload } from '../../../domain/types/v1api'

import { orvalAxiosInstance } from '../../orval/orval-axios-instance'

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Get list
 */
export const getListRawUploads = (
  eventID: string,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal
) => {
  return orvalAxiosInstance<ArraySimpleLog>(
    { url: `/api/v1/events/${eventID}/rawUploads/`, method: 'GET', signal },
    options
  )
}

export const getGetListRawUploadsQueryKey = (eventID: string) => {
  return [`/api/v1/events/${eventID}/rawUploads/`] as const
}

export const getGetListRawUploadsQueryOptions = <
  TData = Awaited<ReturnType<typeof getListRawUploads>>,
  TError = unknown
>(
  eventID: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListRawUploads>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetListRawUploadsQueryKey(eventID)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getListRawUploads>>> = ({ signal }) =>
    getListRawUploads(eventID, requestOptions, signal)

  return { queryKey, queryFn, enabled: !!eventID, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getListRawUploads>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetListRawUploadsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getListRawUploads>>
>
export type GetListRawUploadsQueryError = unknown

export function useGetListRawUploads<
  TData = Awaited<ReturnType<typeof getListRawUploads>>,
  TError = unknown
>(
  eventID: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListRawUploads>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetListRawUploadsQueryOptions(eventID, options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}

export const prefetchGetListRawUploadsQuery = async <
  TData = Awaited<ReturnType<typeof getListRawUploads>>,
  TError = unknown
>(
  queryClient: QueryClient,
  eventID: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListRawUploads>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
): Promise<QueryClient> => {
  const queryOptions = getGetListRawUploadsQueryOptions(eventID, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

/**
 * Get data
 */
export const getRawUploads = (
  eventID: string,
  rawUploadID: string,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal
) => {
  return orvalAxiosInstance<ResRawUpload>(
    { url: `/api/v1/events/${eventID}/rawUploads/${rawUploadID}`, method: 'GET', signal },
    options
  )
}

export const getGetRawUploadsQueryKey = (eventID: string, rawUploadID: string) => {
  return [`/api/v1/events/${eventID}/rawUploads/${rawUploadID}`] as const
}

export const getGetRawUploadsQueryOptions = <
  TData = Awaited<ReturnType<typeof getRawUploads>>,
  TError = unknown
>(
  eventID: string,
  rawUploadID: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getRawUploads>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetRawUploadsQueryKey(eventID, rawUploadID)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRawUploads>>> = ({ signal }) =>
    getRawUploads(eventID, rawUploadID, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!(eventID && rawUploadID),
    ...queryOptions
  } as UseQueryOptions<Awaited<ReturnType<typeof getRawUploads>>, TError, TData> & {
    queryKey: QueryKey
  }
}

export type GetRawUploadsQueryResult = NonNullable<Awaited<ReturnType<typeof getRawUploads>>>
export type GetRawUploadsQueryError = unknown

export function useGetRawUploads<
  TData = Awaited<ReturnType<typeof getRawUploads>>,
  TError = unknown
>(
  eventID: string,
  rawUploadID: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getRawUploads>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetRawUploadsQueryOptions(eventID, rawUploadID, options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}

export const prefetchGetRawUploadsQuery = async <
  TData = Awaited<ReturnType<typeof getRawUploads>>,
  TError = unknown
>(
  queryClient: QueryClient,
  eventID: string,
  rawUploadID: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getRawUploads>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
): Promise<QueryClient> => {
  const queryOptions = getGetRawUploadsQueryOptions(eventID, rawUploadID, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

/**
 * Delete
 */
export const deleteRawUploads = (
  eventID: string,
  rawUploadID: string,
  options?: SecondParameter<typeof orvalAxiosInstance>
) => {
  return orvalAxiosInstance<void>(
    { url: `/api/v1/events/${eventID}/rawUploads/${rawUploadID}`, method: 'DELETE' },
    options
  )
}

export const getDeleteRawUploadsMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteRawUploads>>,
    TError,
    { eventID: string; rawUploadID: string },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteRawUploads>>,
  TError,
  { eventID: string; rawUploadID: string },
  TContext
> => {
  const mutationKey = ['deleteRawUploads']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteRawUploads>>,
    { eventID: string; rawUploadID: string }
  > = (props) => {
    const { eventID, rawUploadID } = props ?? {}

    return deleteRawUploads(eventID, rawUploadID, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteRawUploadsMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteRawUploads>>
>

export type DeleteRawUploadsMutationError = unknown

export const useDeleteRawUploads = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteRawUploads>>,
    TError,
    { eventID: string; rawUploadID: string },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteRawUploads>>,
  TError,
  { eventID: string; rawUploadID: string },
  TContext
> => {
  const mutationOptions = getDeleteRawUploadsMutationOptions(options)

  return useMutation(mutationOptions)
}
