/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type {
  ArrayStageOrderManagement,
  PatchStageOrdersBody,
  PostStageOrdersBody,
  ResStageOrderManagement
} from '../../../domain/types/v1api'

import { orvalAxiosInstance } from '../../orval/orval-axios-instance'

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Get list returns only selected fields
 */
export const getListStageOrders = (
  eventID: string,
  stageID: string,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal
) => {
  return orvalAxiosInstance<ArrayStageOrderManagement>(
    { url: `/api/v1/events/${eventID}/stages/${stageID}/stageOrders/`, method: 'GET', signal },
    options
  )
}

export const getGetListStageOrdersQueryKey = (eventID: string, stageID: string) => {
  return [`/api/v1/events/${eventID}/stages/${stageID}/stageOrders/`] as const
}

export const getGetListStageOrdersQueryOptions = <
  TData = Awaited<ReturnType<typeof getListStageOrders>>,
  TError = unknown
>(
  eventID: string,
  stageID: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListStageOrders>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetListStageOrdersQueryKey(eventID, stageID)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getListStageOrders>>> = ({ signal }) =>
    getListStageOrders(eventID, stageID, requestOptions, signal)

  return { queryKey, queryFn, enabled: !!(eventID && stageID), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getListStageOrders>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetListStageOrdersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getListStageOrders>>
>
export type GetListStageOrdersQueryError = unknown

export function useGetListStageOrders<
  TData = Awaited<ReturnType<typeof getListStageOrders>>,
  TError = unknown
>(
  eventID: string,
  stageID: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListStageOrders>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetListStageOrdersQueryOptions(eventID, stageID, options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}

export const prefetchGetListStageOrdersQuery = async <
  TData = Awaited<ReturnType<typeof getListStageOrders>>,
  TError = unknown
>(
  queryClient: QueryClient,
  eventID: string,
  stageID: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListStageOrders>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
): Promise<QueryClient> => {
  const queryOptions = getGetListStageOrdersQueryOptions(eventID, stageID, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

/**
 * Add new as manager creates in stage
 */
export const postListStageOrders = (
  eventID: string,
  stageID: string,
  postStageOrdersBody: PostStageOrdersBody,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal
) => {
  return orvalAxiosInstance<ResStageOrderManagement>(
    {
      url: `/api/v1/events/${eventID}/stages/${stageID}/stageOrders/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postStageOrdersBody,
      signal
    },
    options
  )
}

export const getPostListStageOrdersMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postListStageOrders>>,
    TError,
    { eventID: string; stageID: string; data: PostStageOrdersBody },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof postListStageOrders>>,
  TError,
  { eventID: string; stageID: string; data: PostStageOrdersBody },
  TContext
> => {
  const mutationKey = ['postListStageOrders']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postListStageOrders>>,
    { eventID: string; stageID: string; data: PostStageOrdersBody }
  > = (props) => {
    const { eventID, stageID, data } = props ?? {}

    return postListStageOrders(eventID, stageID, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostListStageOrdersMutationResult = NonNullable<
  Awaited<ReturnType<typeof postListStageOrders>>
>
export type PostListStageOrdersMutationBody = PostStageOrdersBody
export type PostListStageOrdersMutationError = unknown

export const usePostListStageOrders = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postListStageOrders>>,
    TError,
    { eventID: string; stageID: string; data: PostStageOrdersBody },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationResult<
  Awaited<ReturnType<typeof postListStageOrders>>,
  TError,
  { eventID: string; stageID: string; data: PostStageOrdersBody },
  TContext
> => {
  const mutationOptions = getPostListStageOrdersMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Edit updates editable fields
 */
export const patchStageOrders = (
  eventID: string,
  stageID: string,
  stageOrderID: string,
  patchStageOrdersBody: PatchStageOrdersBody,
  options?: SecondParameter<typeof orvalAxiosInstance>
) => {
  return orvalAxiosInstance<ResStageOrderManagement>(
    {
      url: `/api/v1/events/${eventID}/stages/${stageID}/stageOrders/${stageOrderID}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: patchStageOrdersBody
    },
    options
  )
}

export const getPatchStageOrdersMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchStageOrders>>,
    TError,
    { eventID: string; stageID: string; stageOrderID: string; data: PatchStageOrdersBody },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchStageOrders>>,
  TError,
  { eventID: string; stageID: string; stageOrderID: string; data: PatchStageOrdersBody },
  TContext
> => {
  const mutationKey = ['patchStageOrders']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchStageOrders>>,
    { eventID: string; stageID: string; stageOrderID: string; data: PatchStageOrdersBody }
  > = (props) => {
    const { eventID, stageID, stageOrderID, data } = props ?? {}

    return patchStageOrders(eventID, stageID, stageOrderID, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PatchStageOrdersMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchStageOrders>>
>
export type PatchStageOrdersMutationBody = PatchStageOrdersBody
export type PatchStageOrdersMutationError = unknown

export const usePatchStageOrders = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchStageOrders>>,
    TError,
    { eventID: string; stageID: string; stageOrderID: string; data: PatchStageOrdersBody },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationResult<
  Awaited<ReturnType<typeof patchStageOrders>>,
  TError,
  { eventID: string; stageID: string; stageOrderID: string; data: PatchStageOrdersBody },
  TContext
> => {
  const mutationOptions = getPatchStageOrdersMutationOptions(options)

  return useMutation(mutationOptions)
}
