/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import { useMutation } from '@tanstack/react-query'
import type { MutationFunction, UseMutationOptions, UseMutationResult } from '@tanstack/react-query'

import type { PatchStageOrdersBody, ResStageOrder } from '../../../domain/types/v1api'

import { orvalAxiosInstance } from '../../orval/orval-axios-instance'

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Edit updates description
 */
export const patchStageOrders = (
  eventID: string,
  stageID: string,
  stageOrderID: string,
  patchStageOrdersBody: PatchStageOrdersBody,
  options?: SecondParameter<typeof orvalAxiosInstance>
) => {
  return orvalAxiosInstance<ResStageOrder>(
    {
      url: `/api/v1/events/${eventID}/stages/${stageID}/stageOrders/${stageOrderID}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: patchStageOrdersBody
    },
    options
  )
}

export const getPatchStageOrdersMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchStageOrders>>,
    TError,
    { eventID: string; stageID: string; stageOrderID: string; data: PatchStageOrdersBody },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchStageOrders>>,
  TError,
  { eventID: string; stageID: string; stageOrderID: string; data: PatchStageOrdersBody },
  TContext
> => {
  const mutationKey = ['patchStageOrders']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchStageOrders>>,
    { eventID: string; stageID: string; stageOrderID: string; data: PatchStageOrdersBody }
  > = (props) => {
    const { eventID, stageID, stageOrderID, data } = props ?? {}

    return patchStageOrders(eventID, stageID, stageOrderID, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PatchStageOrdersMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchStageOrders>>
>
export type PatchStageOrdersMutationBody = PatchStageOrdersBody
export type PatchStageOrdersMutationError = unknown

export const usePatchStageOrders = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchStageOrders>>,
    TError,
    { eventID: string; stageID: string; stageOrderID: string; data: PatchStageOrdersBody },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationResult<
  Awaited<ReturnType<typeof patchStageOrders>>,
  TError,
  { eventID: string; stageID: string; stageOrderID: string; data: PatchStageOrdersBody },
  TContext
> => {
  const mutationOptions = getPatchStageOrdersMutationOptions(options)

  return useMutation(mutationOptions)
}
