/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.4
 */
import { useMutation } from '@tanstack/react-query'
import type { MutationFunction, UseMutationOptions, UseMutationResult } from '@tanstack/react-query'

import type { PostListUsersBody, ResUser } from '../../../domain/types/v1api'

import { orvalAxiosInstance } from '../../orval/orval-axios-instance'

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Add new
 */
export const postListUsers = (
  postListUsersBody: PostListUsersBody,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal
) => {
  return orvalAxiosInstance<ResUser>(
    {
      url: `/api/v1/users/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postListUsersBody,
      signal
    },
    options
  )
}

export const getPostListUsersMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postListUsers>>,
    TError,
    { data: PostListUsersBody },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof postListUsers>>,
  TError,
  { data: PostListUsersBody },
  TContext
> => {
  const mutationKey = ['postListUsers']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postListUsers>>,
    { data: PostListUsersBody }
  > = (props) => {
    const { data } = props ?? {}

    return postListUsers(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostListUsersMutationResult = NonNullable<Awaited<ReturnType<typeof postListUsers>>>
export type PostListUsersMutationBody = PostListUsersBody
export type PostListUsersMutationError = unknown

export const usePostListUsers = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postListUsers>>,
    TError,
    { data: PostListUsersBody },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationResult<
  Awaited<ReturnType<typeof postListUsers>>,
  TError,
  { data: PostListUsersBody },
  TContext
> => {
  const mutationOptions = getPostListUsersMutationOptions(options)

  return useMutation(mutationOptions)
}
