/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.4
 */
import { useQuery } from '@tanstack/react-query'
import type {
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type { ResUser } from '../../../domain/types/v1api'

import { orvalAxiosInstance } from '../../orval/orval-axios-instance'

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Get list should get user authenticated with cookie
 */
export const getListMe = (
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal
) => {
  return orvalAxiosInstance<ResUser>({ url: `/api/v1/me/`, method: 'GET', signal }, options)
}

export const getGetListMeQueryKey = () => {
  return [`/api/v1/me/`] as const
}

export const getGetListMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getListMe>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getListMe>>, TError, TData>
  request?: SecondParameter<typeof orvalAxiosInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetListMeQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getListMe>>> = ({ signal }) =>
    getListMe(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getListMe>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetListMeQueryResult = NonNullable<Awaited<ReturnType<typeof getListMe>>>
export type GetListMeQueryError = unknown

export function useGetListMe<
  TData = Awaited<ReturnType<typeof getListMe>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getListMe>>, TError, TData>
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetListMeQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}

export const prefetchGetListMeQuery = async <
  TData = Awaited<ReturnType<typeof getListMe>>,
  TError = unknown
>(
  queryClient: QueryClient,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListMe>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
): Promise<QueryClient> => {
  const queryOptions = getGetListMeQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}
