/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.3
 */
import { useQuery } from '@tanstack/react-query'
import type {
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type { GetListFedoStatsParams, ResFedoStats } from '../../../domain/types/v1api'

import { orvalAxiosInstance } from '../../orval/orval-axios-instance'

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Get list
 */
export const getListFedoStats = (
  eventID: string,
  stageID: string,
  params?: GetListFedoStatsParams,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal
) => {
  return orvalAxiosInstance<ResFedoStats>(
    {
      url: `/api/v1/events/${eventID}/stages/${stageID}/stats-fedo/`,
      method: 'GET',
      params,
      signal
    },
    options
  )
}

export const getGetListFedoStatsQueryKey = (
  eventID: string,
  stageID: string,
  params?: GetListFedoStatsParams
) => {
  return [
    `/api/v1/events/${eventID}/stages/${stageID}/stats-fedo/`,
    ...(params ? [params] : [])
  ] as const
}

export const getGetListFedoStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getListFedoStats>>,
  TError = unknown
>(
  eventID: string,
  stageID: string,
  params?: GetListFedoStatsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListFedoStats>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetListFedoStatsQueryKey(eventID, stageID, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getListFedoStats>>> = ({ signal }) =>
    getListFedoStats(eventID, stageID, params, requestOptions, signal)

  return { queryKey, queryFn, enabled: !!(eventID && stageID), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getListFedoStats>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetListFedoStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getListFedoStats>>>
export type GetListFedoStatsQueryError = unknown

export function useGetListFedoStats<
  TData = Awaited<ReturnType<typeof getListFedoStats>>,
  TError = unknown
>(
  eventID: string,
  stageID: string,
  params?: GetListFedoStatsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListFedoStats>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetListFedoStatsQueryOptions(eventID, stageID, params, options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}

export const prefetchGetListFedoStatsQuery = async <
  TData = Awaited<ReturnType<typeof getListFedoStats>>,
  TError = unknown
>(
  queryClient: QueryClient,
  eventID: string,
  stageID: string,
  params?: GetListFedoStatsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListFedoStats>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
): Promise<QueryClient> => {
  const queryOptions = getGetListFedoStatsQueryOptions(eventID, stageID, params, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}
