/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import { useQuery } from '@tanstack/react-query'
import type {
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type { ArrayRunnerSearch, GetListRunnerSearchParams } from '../../../domain/types/v1api'

import { orvalAxiosInstance } from '../../orval/orval-axios-instance'

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Search by first name
 */
export const getListRunnerSearch = (
  params?: GetListRunnerSearchParams,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal
) => {
  return orvalAxiosInstance<ArrayRunnerSearch>(
    { url: `/api/v1/runners/search/`, method: 'GET', params, signal },
    options
  )
}

export const getGetListRunnerSearchQueryKey = (params?: GetListRunnerSearchParams) => {
  return [`/api/v1/runners/search/`, ...(params ? [params] : [])] as const
}

export const getGetListRunnerSearchQueryOptions = <
  TData = Awaited<ReturnType<typeof getListRunnerSearch>>,
  TError = unknown
>(
  params?: GetListRunnerSearchParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListRunnerSearch>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetListRunnerSearchQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getListRunnerSearch>>> = ({ signal }) =>
    getListRunnerSearch(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getListRunnerSearch>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetListRunnerSearchQueryResult = NonNullable<
  Awaited<ReturnType<typeof getListRunnerSearch>>
>
export type GetListRunnerSearchQueryError = unknown

export function useGetListRunnerSearch<
  TData = Awaited<ReturnType<typeof getListRunnerSearch>>,
  TError = unknown
>(
  params?: GetListRunnerSearchParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListRunnerSearch>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetListRunnerSearchQueryOptions(params, options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}

export const prefetchGetListRunnerSearchQuery = async <
  TData = Awaited<ReturnType<typeof getListRunnerSearch>>,
  TError = unknown
>(
  queryClient: QueryClient,
  params?: GetListRunnerSearchParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListRunnerSearch>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
): Promise<QueryClient> => {
  const queryOptions = getGetListRunnerSearchQueryOptions(params, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}
