/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import { useQuery } from '@tanstack/react-query'
import type {
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type { ArrayClassEntity } from '../../../domain/types/v1api'

import { orvalAxiosInstance } from '../../orval/orval-axios-instance'

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Get list
 */
export const getListStageClasses = (
  eventID: string,
  stageID: string,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal
) => {
  return orvalAxiosInstance<ArrayClassEntity>(
    { url: `/api/v1/events/${eventID}/stages/${stageID}/classes/`, method: 'GET', signal },
    options
  )
}

export const getGetListStageClassesQueryKey = (eventID: string, stageID: string) => {
  return [`/api/v1/events/${eventID}/stages/${stageID}/classes/`] as const
}

export const getGetListStageClassesQueryOptions = <
  TData = Awaited<ReturnType<typeof getListStageClasses>>,
  TError = unknown
>(
  eventID: string,
  stageID: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListStageClasses>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetListStageClassesQueryKey(eventID, stageID)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getListStageClasses>>> = ({ signal }) =>
    getListStageClasses(eventID, stageID, requestOptions, signal)

  return { queryKey, queryFn, enabled: !!(eventID && stageID), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getListStageClasses>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetListStageClassesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getListStageClasses>>
>
export type GetListStageClassesQueryError = unknown

export function useGetListStageClasses<
  TData = Awaited<ReturnType<typeof getListStageClasses>>,
  TError = unknown
>(
  eventID: string,
  stageID: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListStageClasses>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetListStageClassesQueryOptions(eventID, stageID, options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}

export const prefetchGetListStageClassesQuery = async <
  TData = Awaited<ReturnType<typeof getListStageClasses>>,
  TError = unknown
>(
  queryClient: QueryClient,
  eventID: string,
  stageID: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListStageClasses>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
): Promise<QueryClient> => {
  const queryOptions = getGetListStageClassesQueryOptions(eventID, stageID, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}
