/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import { useMutation } from '@tanstack/react-query'
import type { MutationFunction, UseMutationOptions, UseMutationResult } from '@tanstack/react-query'

import type { PdfRequest, ResPdfBook } from '../../../domain/types/v1api'

import { orvalAxiosInstance } from '../../orval/orval-axios-instance'

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Post run dry echoes the validated book as json instead of rendering it
 */
export const postListPdf = (
  pdfRequest: PdfRequest,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal
) => {
  return orvalAxiosInstance<ResPdfBook>(
    {
      url: `/api/v1/pdf/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: pdfRequest,
      signal
    },
    options
  )
}

export const getPostListPdfMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postListPdf>>,
    TError,
    { data: PdfRequest },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof postListPdf>>,
  TError,
  { data: PdfRequest },
  TContext
> => {
  const mutationKey = ['postListPdf']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postListPdf>>,
    { data: PdfRequest }
  > = (props) => {
    const { data } = props ?? {}

    return postListPdf(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostListPdfMutationResult = NonNullable<Awaited<ReturnType<typeof postListPdf>>>
export type PostListPdfMutationBody = PdfRequest
export type PostListPdfMutationError = unknown

export const usePostListPdf = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postListPdf>>,
    TError,
    { data: PdfRequest },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationResult<
  Awaited<ReturnType<typeof postListPdf>>,
  TError,
  { data: PdfRequest },
  TContext
> => {
  const mutationOptions = getPostListPdfMutationOptions(options)

  return useMutation(mutationOptions)
}
