/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type {
  ArrayRankingOrganizer,
  PostListRankingOrganizersBody,
  ResRankingOrganizer
} from '../../../domain/types/v1api'

import { orvalAxiosInstance } from '../../orval/orval-axios-instance'

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Add new with existing runner id
 */
export const postListRankingOrganizers = (
  rankingID: string,
  eventID: string,
  stageID: string,
  stageOrderID: string,
  postListRankingOrganizersBody: PostListRankingOrganizersBody,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal
) => {
  return orvalAxiosInstance<ResRankingOrganizer>(
    {
      url: `/api/v1/rankings/${rankingID}/events/${eventID}/stages/${stageID}/stageOrders/${stageOrderID}/organizers/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postListRankingOrganizersBody,
      signal
    },
    options
  )
}

export const getPostListRankingOrganizersMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postListRankingOrganizers>>,
    TError,
    {
      rankingID: string
      eventID: string
      stageID: string
      stageOrderID: string
      data: PostListRankingOrganizersBody
    },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof postListRankingOrganizers>>,
  TError,
  {
    rankingID: string
    eventID: string
    stageID: string
    stageOrderID: string
    data: PostListRankingOrganizersBody
  },
  TContext
> => {
  const mutationKey = ['postListRankingOrganizers']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postListRankingOrganizers>>,
    {
      rankingID: string
      eventID: string
      stageID: string
      stageOrderID: string
      data: PostListRankingOrganizersBody
    }
  > = (props) => {
    const { rankingID, eventID, stageID, stageOrderID, data } = props ?? {}

    return postListRankingOrganizers(
      rankingID,
      eventID,
      stageID,
      stageOrderID,
      data,
      requestOptions
    )
  }

  return { mutationFn, ...mutationOptions }
}

export type PostListRankingOrganizersMutationResult = NonNullable<
  Awaited<ReturnType<typeof postListRankingOrganizers>>
>
export type PostListRankingOrganizersMutationBody = PostListRankingOrganizersBody
export type PostListRankingOrganizersMutationError = unknown

export const usePostListRankingOrganizers = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postListRankingOrganizers>>,
    TError,
    {
      rankingID: string
      eventID: string
      stageID: string
      stageOrderID: string
      data: PostListRankingOrganizersBody
    },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationResult<
  Awaited<ReturnType<typeof postListRankingOrganizers>>,
  TError,
  {
    rankingID: string
    eventID: string
    stageID: string
    stageOrderID: string
    data: PostListRankingOrganizersBody
  },
  TContext
> => {
  const mutationOptions = getPostListRankingOrganizersMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Get list returns organizers
 */
export const getListRankingOrganizers = (
  rankingID: string,
  eventID: string,
  stageID: string,
  stageOrderID: string,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal
) => {
  return orvalAxiosInstance<ArrayRankingOrganizer>(
    {
      url: `/api/v1/rankings/${rankingID}/events/${eventID}/stages/${stageID}/stageOrders/${stageOrderID}/organizers/`,
      method: 'GET',
      signal
    },
    options
  )
}

export const getGetListRankingOrganizersQueryKey = (
  rankingID: string,
  eventID: string,
  stageID: string,
  stageOrderID: string
) => {
  return [
    `/api/v1/rankings/${rankingID}/events/${eventID}/stages/${stageID}/stageOrders/${stageOrderID}/organizers/`
  ] as const
}

export const getGetListRankingOrganizersQueryOptions = <
  TData = Awaited<ReturnType<typeof getListRankingOrganizers>>,
  TError = unknown
>(
  rankingID: string,
  eventID: string,
  stageID: string,
  stageOrderID: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListRankingOrganizers>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetListRankingOrganizersQueryKey(rankingID, eventID, stageID, stageOrderID)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getListRankingOrganizers>>> = ({
    signal
  }) => getListRankingOrganizers(rankingID, eventID, stageID, stageOrderID, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!(rankingID && eventID && stageID && stageOrderID),
    ...queryOptions
  } as UseQueryOptions<Awaited<ReturnType<typeof getListRankingOrganizers>>, TError, TData> & {
    queryKey: QueryKey
  }
}

export type GetListRankingOrganizersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getListRankingOrganizers>>
>
export type GetListRankingOrganizersQueryError = unknown

export function useGetListRankingOrganizers<
  TData = Awaited<ReturnType<typeof getListRankingOrganizers>>,
  TError = unknown
>(
  rankingID: string,
  eventID: string,
  stageID: string,
  stageOrderID: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListRankingOrganizers>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetListRankingOrganizersQueryOptions(
    rankingID,
    eventID,
    stageID,
    stageOrderID,
    options
  )

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}

export const prefetchGetListRankingOrganizersQuery = async <
  TData = Awaited<ReturnType<typeof getListRankingOrganizers>>,
  TError = unknown
>(
  queryClient: QueryClient,
  rankingID: string,
  eventID: string,
  stageID: string,
  stageOrderID: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListRankingOrganizers>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
): Promise<QueryClient> => {
  const queryOptions = getGetListRankingOrganizersQueryOptions(
    rankingID,
    eventID,
    stageID,
    stageOrderID,
    options
  )

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

/**
 * Delete soft deletes organizer
 */
export const deleteRankingOrganizers = (
  rankingID: string,
  eventID: string,
  stageID: string,
  stageOrderID: string,
  organizerID: string,
  options?: SecondParameter<typeof orvalAxiosInstance>
) => {
  return orvalAxiosInstance<void>(
    {
      url: `/api/v1/rankings/${rankingID}/events/${eventID}/stages/${stageID}/stageOrders/${stageOrderID}/organizers/${organizerID}`,
      method: 'DELETE'
    },
    options
  )
}

export const getDeleteRankingOrganizersMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteRankingOrganizers>>,
    TError,
    {
      rankingID: string
      eventID: string
      stageID: string
      stageOrderID: string
      organizerID: string
    },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteRankingOrganizers>>,
  TError,
  {
    rankingID: string
    eventID: string
    stageID: string
    stageOrderID: string
    organizerID: string
  },
  TContext
> => {
  const mutationKey = ['deleteRankingOrganizers']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteRankingOrganizers>>,
    {
      rankingID: string
      eventID: string
      stageID: string
      stageOrderID: string
      organizerID: string
    }
  > = (props) => {
    const { rankingID, eventID, stageID, stageOrderID, organizerID } = props ?? {}

    return deleteRankingOrganizers(
      rankingID,
      eventID,
      stageID,
      stageOrderID,
      organizerID,
      requestOptions
    )
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteRankingOrganizersMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteRankingOrganizers>>
>

export type DeleteRankingOrganizersMutationError = unknown

export const useDeleteRankingOrganizers = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteRankingOrganizers>>,
    TError,
    {
      rankingID: string
      eventID: string
      stageID: string
      stageOrderID: string
      organizerID: string
    },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteRankingOrganizers>>,
  TError,
  {
    rankingID: string
    eventID: string
    stageID: string
    stageOrderID: string
    organizerID: string
  },
  TContext
> => {
  const mutationOptions = getDeleteRankingOrganizersMutationOptions(options)

  return useMutation(mutationOptions)
}
