/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type {
  ArrayOrganizer,
  PatchOrganizersManagementBody,
  PostListOrganizersManagementBody,
  ResOrganizer
} from '../../../domain/types/v1api'

import { orvalAxiosInstance } from '../../orval/orval-axios-instance'

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Get list returns organizers ordered by name
 */
export const getListOrganizersManagement = (
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal
) => {
  return orvalAxiosInstance<ArrayOrganizer>(
    { url: `/api/v1/organizersManagement/`, method: 'GET', signal },
    options
  )
}

export const getGetListOrganizersManagementQueryKey = () => {
  return [`/api/v1/organizersManagement/`] as const
}

export const getGetListOrganizersManagementQueryOptions = <
  TData = Awaited<ReturnType<typeof getListOrganizersManagement>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getListOrganizersManagement>>, TError, TData>
  request?: SecondParameter<typeof orvalAxiosInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetListOrganizersManagementQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getListOrganizersManagement>>> = ({
    signal
  }) => getListOrganizersManagement(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getListOrganizersManagement>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetListOrganizersManagementQueryResult = NonNullable<
  Awaited<ReturnType<typeof getListOrganizersManagement>>
>
export type GetListOrganizersManagementQueryError = unknown

export function useGetListOrganizersManagement<
  TData = Awaited<ReturnType<typeof getListOrganizersManagement>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getListOrganizersManagement>>, TError, TData>
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetListOrganizersManagementQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}

export const prefetchGetListOrganizersManagementQuery = async <
  TData = Awaited<ReturnType<typeof getListOrganizersManagement>>,
  TError = unknown
>(
  queryClient: QueryClient,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListOrganizersManagement>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
): Promise<QueryClient> => {
  const queryOptions = getGetListOrganizersManagementQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

/**
 * Add new generates uuid server side
 */
export const postListOrganizersManagement = (
  postListOrganizersManagementBody: PostListOrganizersManagementBody,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal
) => {
  return orvalAxiosInstance<ResOrganizer>(
    {
      url: `/api/v1/organizersManagement/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postListOrganizersManagementBody,
      signal
    },
    options
  )
}

export const getPostListOrganizersManagementMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postListOrganizersManagement>>,
    TError,
    { data: PostListOrganizersManagementBody },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof postListOrganizersManagement>>,
  TError,
  { data: PostListOrganizersManagementBody },
  TContext
> => {
  const mutationKey = ['postListOrganizersManagement']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postListOrganizersManagement>>,
    { data: PostListOrganizersManagementBody }
  > = (props) => {
    const { data } = props ?? {}

    return postListOrganizersManagement(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostListOrganizersManagementMutationResult = NonNullable<
  Awaited<ReturnType<typeof postListOrganizersManagement>>
>
export type PostListOrganizersManagementMutationBody = PostListOrganizersManagementBody
export type PostListOrganizersManagementMutationError = unknown

export const usePostListOrganizersManagement = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postListOrganizersManagement>>,
    TError,
    { data: PostListOrganizersManagementBody },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationResult<
  Awaited<ReturnType<typeof postListOrganizersManagement>>,
  TError,
  { data: PostListOrganizersManagementBody },
  TContext
> => {
  const mutationOptions = getPostListOrganizersManagementMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Edit updates organizer
 */
export const patchOrganizersManagement = (
  organizersManagementID: string,
  patchOrganizersManagementBody: PatchOrganizersManagementBody,
  options?: SecondParameter<typeof orvalAxiosInstance>
) => {
  return orvalAxiosInstance<ResOrganizer>(
    {
      url: `/api/v1/organizersManagement/${organizersManagementID}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: patchOrganizersManagementBody
    },
    options
  )
}

export const getPatchOrganizersManagementMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchOrganizersManagement>>,
    TError,
    { organizersManagementID: string; data: PatchOrganizersManagementBody },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchOrganizersManagement>>,
  TError,
  { organizersManagementID: string; data: PatchOrganizersManagementBody },
  TContext
> => {
  const mutationKey = ['patchOrganizersManagement']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchOrganizersManagement>>,
    { organizersManagementID: string; data: PatchOrganizersManagementBody }
  > = (props) => {
    const { organizersManagementID, data } = props ?? {}

    return patchOrganizersManagement(organizersManagementID, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PatchOrganizersManagementMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchOrganizersManagement>>
>
export type PatchOrganizersManagementMutationBody = PatchOrganizersManagementBody
export type PatchOrganizersManagementMutationError = unknown

export const usePatchOrganizersManagement = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchOrganizersManagement>>,
    TError,
    { organizersManagementID: string; data: PatchOrganizersManagementBody },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationResult<
  Awaited<ReturnType<typeof patchOrganizersManagement>>,
  TError,
  { organizersManagementID: string; data: PatchOrganizersManagementBody },
  TContext
> => {
  const mutationOptions = getPatchOrganizersManagementMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Delete soft deletes organizer
 */
export const deleteOrganizersManagement = (
  organizersManagementID: string,
  options?: SecondParameter<typeof orvalAxiosInstance>
) => {
  return orvalAxiosInstance<void>(
    { url: `/api/v1/organizersManagement/${organizersManagementID}`, method: 'DELETE' },
    options
  )
}

export const getDeleteOrganizersManagementMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteOrganizersManagement>>,
    TError,
    { organizersManagementID: string },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteOrganizersManagement>>,
  TError,
  { organizersManagementID: string },
  TContext
> => {
  const mutationKey = ['deleteOrganizersManagement']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteOrganizersManagement>>,
    { organizersManagementID: string }
  > = (props) => {
    const { organizersManagementID } = props ?? {}

    return deleteOrganizersManagement(organizersManagementID, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteOrganizersManagementMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteOrganizersManagement>>
>

export type DeleteOrganizersManagementMutationError = unknown

export const useDeleteOrganizersManagement = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteOrganizersManagement>>,
    TError,
    { organizersManagementID: string },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteOrganizersManagement>>,
  TError,
  { organizersManagementID: string },
  TContext
> => {
  const mutationOptions = getDeleteOrganizersManagementMutationOptions(options)

  return useMutation(mutationOptions)
}
