/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import { useMutation } from '@tanstack/react-query'
import type { MutationFunction, UseMutationOptions, UseMutationResult } from '@tanstack/react-query'

import type {
  PostListUploadsParams,
  ResUploaded,
  UploadPostData
} from '../../../domain/types/v1api'

import { orvalAxiosInstance } from '../../orval/orval-axios-instance'

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Add new on error
 */
export const postListUploads = (
  eventID: string,
  uploadPostData: UploadPostData,
  params?: PostListUploadsParams,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal
) => {
  return orvalAxiosInstance<ResUploaded>(
    {
      url: `/api/v1/events/${eventID}/uploads/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: uploadPostData,
      params,
      signal
    },
    options
  )
}

export const getPostListUploadsMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postListUploads>>,
    TError,
    { eventID: string; data: UploadPostData; params?: PostListUploadsParams },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof postListUploads>>,
  TError,
  { eventID: string; data: UploadPostData; params?: PostListUploadsParams },
  TContext
> => {
  const mutationKey = ['postListUploads']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postListUploads>>,
    { eventID: string; data: UploadPostData; params?: PostListUploadsParams }
  > = (props) => {
    const { eventID, data, params } = props ?? {}

    return postListUploads(eventID, data, params, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostListUploadsMutationResult = NonNullable<Awaited<ReturnType<typeof postListUploads>>>
export type PostListUploadsMutationBody = UploadPostData
export type PostListUploadsMutationError = unknown

export const usePostListUploads = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postListUploads>>,
    TError,
    { eventID: string; data: UploadPostData; params?: PostListUploadsParams },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationResult<
  Awaited<ReturnType<typeof postListUploads>>,
  TError,
  { eventID: string; data: UploadPostData; params?: PostListUploadsParams },
  TContext
> => {
  const mutationOptions = getPostListUploadsMutationOptions(options)

  return useMutation(mutationOptions)
}
