/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.3
 */
import { useQuery } from '@tanstack/react-query'
import type {
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type { ArrayOrganizer } from '../../../domain/types/v1api'

import { orvalAxiosInstance } from '../../orval/orval-axios-instance'

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Get list
 */
export const getListOrganizers = (
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal
) => {
  return orvalAxiosInstance<ArrayOrganizer>(
    { url: `/api/v1/organizers/`, method: 'GET', signal },
    options
  )
}

export const getGetListOrganizersQueryKey = () => {
  return [`/api/v1/organizers/`] as const
}

export const getGetListOrganizersQueryOptions = <
  TData = Awaited<ReturnType<typeof getListOrganizers>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getListOrganizers>>, TError, TData>
  request?: SecondParameter<typeof orvalAxiosInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetListOrganizersQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getListOrganizers>>> = ({ signal }) =>
    getListOrganizers(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getListOrganizers>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetListOrganizersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getListOrganizers>>
>
export type GetListOrganizersQueryError = unknown

export function useGetListOrganizers<
  TData = Awaited<ReturnType<typeof getListOrganizers>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getListOrganizers>>, TError, TData>
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetListOrganizersQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey }

  query.queryKey = queryOptions.queryKey

  return query
}

export const prefetchGetListOrganizersQuery = async <
  TData = Awaited<ReturnType<typeof getListOrganizers>>,
  TError = unknown
>(
  queryClient: QueryClient,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getListOrganizers>>, TError, TData>
    request?: SecondParameter<typeof orvalAxiosInstance>
  }
): Promise<QueryClient> => {
  const queryOptions = getGetListOrganizersQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}
