/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import { useMutation } from '@tanstack/react-query'
import type { MutationFunction, UseMutationOptions, UseMutationResult } from '@tanstack/react-query'

import type {
  PostListUploadsV2Params,
  ResUploadedV2,
  UploadPostData
} from '../../../domain/types/v1api'

import { orvalAxiosInstance } from '../../orval/orval-axios-instance'

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Add new should add mixed content
 */
export const postListUploadsV2 = (
  eventID: string,
  uploadPostData: UploadPostData,
  params?: PostListUploadsV2Params,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal
) => {
  return orvalAxiosInstance<ResUploadedV2>(
    {
      url: `/api/v1/events/${eventID}/uploads/v2/`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: uploadPostData,
      params,
      signal
    },
    options
  )
}

export const getPostListUploadsV2MutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postListUploadsV2>>,
    TError,
    { eventID: string; data: UploadPostData; params?: PostListUploadsV2Params },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof postListUploadsV2>>,
  TError,
  { eventID: string; data: UploadPostData; params?: PostListUploadsV2Params },
  TContext
> => {
  const mutationKey = ['postListUploadsV2']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postListUploadsV2>>,
    { eventID: string; data: UploadPostData; params?: PostListUploadsV2Params }
  > = (props) => {
    const { eventID, data, params } = props ?? {}

    return postListUploadsV2(eventID, data, params, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostListUploadsV2MutationResult = NonNullable<
  Awaited<ReturnType<typeof postListUploadsV2>>
>
export type PostListUploadsV2MutationBody = UploadPostData
export type PostListUploadsV2MutationError = unknown

export const usePostListUploadsV2 = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postListUploadsV2>>,
    TError,
    { eventID: string; data: UploadPostData; params?: PostListUploadsV2Params },
    TContext
  >
  request?: SecondParameter<typeof orvalAxiosInstance>
}): UseMutationResult<
  Awaited<ReturnType<typeof postListUploadsV2>>,
  TError,
  { eventID: string; data: UploadPostData; params?: PostListUploadsV2Params },
  TContext
> => {
  const mutationOptions = getPostListUploadsV2MutationOptions(options)

  return useMutation(mutationOptions)
}
