/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { SimpleLog } from './simpleLog'

/**
 * Data wrapper for SimpleLog
 */
export interface ArraySimpleLog {
  data: SimpleLog[]
}
