/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { ClassEntity } from './classEntity'

/**
 * Data wrapper for ClassEntity
 */
export interface ArrayClassEntity {
  data: ClassEntity[]
}
