/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { RunnerSearch } from './runnerSearch'

/**
 * Data wrapper for RunnerSearch
 */
export interface ArrayRunnerSearch {
  data: RunnerSearch[]
}
