/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { Participant } from './participant'

/**
 * Data wrapper for Participant
 */
export interface ArrayParticipant {
  data: Participant[]
}
