/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { Organizer } from './organizer'

/**
 * Data wrapper for Organizer
 */
export interface ArrayOrganizer {
  data: Organizer[]
}
