/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { StageOrderManagement } from './stageOrderManagement'

/**
 * Data wrapper for StageOrderManagement
 */
export interface ArrayStageOrderManagement {
  data: StageOrderManagement[]
}
