/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { Participant } from './participant'
import type { Split } from './split'

/**
 * Entity ClassEntity
 */
export interface ClassEntity {
  id: string
  long_name: string
  runners?: Participant[]
  short_name: string
  splits?: Split[]
}
