/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.3
 */
import type { Participant } from './participant'
import type { Split } from './split'

/**
 * Entity ClassEntity
 */
export interface ClassEntity {
  id: string
  short_name: string
  long_name: string
  runners?: Participant[]
  splits?: Split[]
}
