/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */

/**
 * Entity Club
 */
export interface Club {
  /** @nullable */
  city?: string | null
  id: string
  /** @nullable */
  province?: string | null
  /** @nullable */
  region?: string | null
  short_name: string
}
