/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.3
 */
import type { ControlType } from './controlType'

/**
 * Entity Control
 */
export interface Control {
  id: string
  station: number
  control_type: ControlType
}
