/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { ControlType } from './controlType'

/**
 * Entity Control
 */
export interface Control {
  id: string
  station: number
  control_type: ControlType
}
