/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.3
 */
import type { Organizer } from './organizer'
import type { _EventLinks } from './_eventLinks'
import type { EventUsersItem } from './eventUsersItem'
import type { Stage } from './stage'
import type { Federation } from './federation'

/**
 * Entity Event
 */
export interface Event {
  id: string
  is_hidden?: boolean
  description: string
  /** @nullable */
  picture?: string | null
  /** @nullable */
  website?: string | null
  /** @nullable */
  scope?: string | null
  /** @nullable */
  location?: string | null
  /** @nullable */
  country_code?: string | null
  initial_date: string
  final_date: string
  federation_id: string
  created: string
  modified: string
  organizer_id: string
  organizer?: Organizer
  /** Generic object. */
  _links: _EventLinks
  users?: EventUsersItem[]
  stages?: Stage[]
  federation?: Federation
}
