/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { Organizer } from './organizer'
import type { LinkUri } from './linkUri'
import type { Stage } from './stage'
import type { Federation } from './federation'

/**
 * Entity Event
 */
export interface Event {
  id: string
  is_hidden?: boolean
  description: string
  /** @nullable */
  picture?: string | null
  /** @nullable */
  website?: string | null
  /** @nullable */
  scope?: string | null
  /** @nullable */
  location?: string | null
  /** @nullable */
  country_code?: string | null
  initial_date: string
  final_date: string
  timezone?: string
  federation_id: string
  created: string
  modified: string
  organizer_id: string
  organizer?: Organizer
  _links: LinkUri
  stages?: Stage[]
  federation?: Federation
}
