/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { GenderGrouped } from './genderGrouped'

/**
 * Entity FedoStats
 */
export interface FedoStats {
  officialSenior?: GenderGrouped
  officialSub20?: GenderGrouped
  others?: GenderGrouped
}
