/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.4
 */

export type GetListResultsParams = {
  class_id?: string
  club_id?: string
  station?: string
  output?: string
  text?: string
}
