/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.3
 */

export type GetListFedoStatsParams = {
  officialSeniorM?: string
  officialSeniorF?: string
  officialSub20M?: string
  officialSub20F?: string
}
