/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */

export type GetListEventsParams = {
  user_id?: string
  show_hidden?: string
  description?: string
  page?: string
  limit?: string
  when?: string
  'initial_date:lte'?: string
  'final_date:gte'?: string
}
