/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */

export type GetListResultsParams = {
  class_id?: string
  club_id?: string
  station?: string
  output?: string
  text?: string
}
