/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.3
 */

export type GetListEventsParams = {
  user_id?: string
  description?: string
  page?: string
  limit?: string
  when?: string
  show_hidden?: string
  'initial_date:lte'?: string
  'final_date:gte'?: string
}
