/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.3
 */
import type { LinkHref } from './linkHref'

/**
 * Entity LinkUri
 */
export interface LinkUri {
  self: LinkHref
}
