/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */

/**
 * Entity Organizer
 */
export interface Organizer {
  city?: string
  country_code: string
  id: string
  name: string
  province?: string
  region: string
  region_code: string
}
