/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.4
 */

/**
 * Entity Organizer
 */
export interface Organizer {
  id: string
  name: string
  country: string
  region: string
}
