/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */

/**
 * Entity Organizer
 */
export interface Organizer {
  id: string
  name: string
  country: string
  region: string
}
