/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { PartialOverall } from './partialOverall'

/**
 * Entity Overalls
 */
export interface Overalls {
  parts?: PartialOverall[]
  overall?: PartialOverall
}
