/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { PaginationLinksSelf } from './paginationLinksSelf'
import type { PaginationLinksNext } from './paginationLinksNext'
import type { PaginationLinksPrev } from './paginationLinksPrev'

/**
 * Pagination links.
 */
export interface PaginationLinks {
  /** Generic object. */
  self?: PaginationLinksSelf
  /** Generic object. */
  next?: PaginationLinksNext
  /** Generic object. */
  prev?: PaginationLinksPrev
}
