/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { PaginationLinks } from './paginationLinks'
import type { Ranking } from './ranking'

/**
 * Paginated Ranking
 */
export interface PaginatedRanking {
  _links: PaginationLinks
  data: Ranking[]
  limit: number
  total: number
}
