/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.4
 */
import type { Event } from './event'
import type { PaginationLinks } from './paginationLinks'

/**
 * Paginated Event
 */
export interface PaginatedEvent {
  data: Event[]
  total: number
  limit: number
  _links: PaginationLinks
}
