/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { Event } from './event'
import type { PaginationLinks } from './paginationLinks'

/**
 * Paginated Event
 */
export interface PaginatedEvent {
  data: Event[]
  total: number
  limit: number
  _links: PaginationLinks
}
