/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.3
 */
import type { PaginationLinksSelf } from './paginationLinksSelf'
import type { PaginationLinksNext } from './paginationLinksNext'
import type { PaginationLinksPrev } from './paginationLinksPrev'

/**
 * Pagination links.
 */
export interface PaginationLinks {
  /** Generic object. */
  self?: PaginationLinksSelf
  /** Generic object. */
  next?: PaginationLinksNext
  /** Generic object. */
  prev?: PaginationLinksPrev
}
