/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.3
 */
import type { ClassEntity } from './classEntity'
import type { Club } from './club'
import type { Result } from './result'

/**
 * Entity Participant
 */
export interface Participant {
  id: string
  bib_number: number
  is_nc: boolean
  eligibility: string
  /** @nullable */
  legs?: string | null
  created: string
  sicard?: number
  /** @nullable */
  sex?: string | null
  /** @nullable */
  leg_number?: string | null
  /** @nullable */
  class?: ClassEntity
  club: Club
  full_name: string
  /** @nullable */
  stage?: Result
  /** @nullable */
  overalls?: string | null
  runners?: Participant[]
}
