/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { StageOrder } from './stageOrder'

/**
 * Entity PartialOverall
 */
export interface PartialOverall {
  id: string
  stage_order: number
  upload_type: string
  /** @nullable */
  stage?: StageOrder
  position: number
  status_code: number
  /** @nullable */
  is_nc?: string | null
  /** @nullable */
  contributory?: boolean | null
  /** @nullable */
  time_seconds?: string | null
  /** @nullable */
  time_behind?: string | null
  points_final: number
  /** @nullable */
  points_behind?: string | null
  /** @nullable */
  note?: string | null
}
