/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { ClassEntity } from './classEntity'
import type { Club } from './club'
import type { Overalls } from './overalls'
import type { Result } from './result'

/**
 * Entity Participant
 */
export interface Participant {
  bib_number: number
  /** @nullable */
  class?: ClassEntity
  club: Club
  created: string
  eligibility: string
  full_name: string
  id: string
  is_nc: boolean
  /** @nullable */
  leg_number?: string | null
  /** @nullable */
  legs?: string | null
  /** @nullable */
  overalls?: Overalls
  runners?: Participant[]
  /** @nullable */
  sex?: string | null
  sicard?: number
  /** @nullable */
  stage?: Result
}
