/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.3
 */

/**
 * Entity PatchStagesBody
 */
export interface PatchStagesBody {
  description?: string
  stage_type_id?: string
  state_end?: number
}
