/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */

/**
 * Generic object when: Edit updates organizer
 */
export type PatchOrganizersManagementBody = {
  country_code?: string
  region_code?: string
}
