/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */

/**
 * Generic object when: Edit
 */
export type PatchEventsBody = {
  is_hidden?: number
  description?: string
  scope?: string
  location?: string
  country_code?: string
  website?: string
  picture?: string
  initial_date?: string
  final_date?: string
}
