/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */

/**
 * Entity PatchStageOrdersBody
 */
export interface PatchStageOrdersBody {
  description?: string
  is_official?: boolean
  original_event_id?: string
  original_stage_id?: string
  start?: string
}
