/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { PdfSection } from './pdfSection'

/**
 * Entity PdfBook
 */
export interface PdfBook {
  filename?: string
  layout?: string
  sections?: PdfSection[]
}
