/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { PdfPosition } from './pdfPosition'

/**
 * Entity PdfElement
 */
export interface PdfElement {
  content?: string
  position?: PdfPosition
  size?: number
  type?: string
}
