/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { PdfBook } from './pdfBook'

/**
 * Entity PdfRequest
 */
export interface PdfRequest {
  pdfBook?: PdfBook
  runDry?: boolean
}
