/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */

/**
 * Generic object when: Add new generates uuid server side
 */
export type PostListOrganizersManagementBody = {
  country?: string
  name?: string
  region?: string
}
