/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */

/**
 * Entity PostListStagesBody
 */
export interface PostListStagesBody {
  description?: string
  stage_type_id?: string
  start?: string
}
