/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */

/**
 * Generic object when: Add new
 */
export type PostListEventsBody = {
  country_code?: string
  description?: string
  federation_id?: string
  final_date?: string
  id?: string
  initial_date?: string
  is_hidden?: boolean
  location?: string
  organizer_id?: string
  picture?: string
  scope?: string
  timezone?: string
  website?: string
}
