/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */

/**
 * Generic object when: Add new
 */
export type PostListUsersBody = {
  email?: string
  first_name?: string
  last_name?: string
  password?: string
}
