/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */

/**
 * Generic object when: Add new with existing runner id
 */
export type PostListRankingOrganizersBody = {
  description?: string
  first_name?: string
  last_name?: string
  runner_id?: string
}
