/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */

/**
 * Generic object when: Add new only class list
 */
export type PostListRankingComputeStageBody = {
  classes?: string
}
