/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.4
 */

/**
 * Generic object when: Add new
 */
export type PostListUsersBody = {
  email?: string
  first_name?: string
  last_name?: string
  password?: string
}
