/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */

/**
 * Entity PostStageOrdersBody
 */
export interface PostStageOrdersBody {
  description?: string
  is_official?: number
  original_event_id?: string
  original_stage_id?: string
  stage_order?: number
  start?: string
}
