/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */

/**
 * Generic object when: Add new creates ranking
 */
export type PostListRankingSettingsBody = {
  event_id?: string
  id?: string
  max_points?: number
  round_precision?: number
  scoring_algorithm?: string
  stage_id?: string
}
