/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */

/**
 * Generic object when: Add new
 */
export type PostListRankingRunnerManagementBody = {
  runner_id?: string
  stage_order?: number
  upload_type?: string
}
