/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { LinkHref } from './linkHref'

/**
 * Entity RankingLinks
 */
export interface RankingLinks {
  results?: LinkHref
  self?: LinkHref
}
