/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { RankingLinks } from './rankingLinks'

/**
 * Entity Ranking
 */
export interface Ranking {
  _links: RankingLinks
  created: string
  event_id: string
  /** @nullable */
  excluded_class_names?: string | null
  id: string
  /** @nullable */
  included_class_names?: string | null
  max_points: number
  modified: string
  /** @nullable */
  nc_false?: number | null
  /** @nullable */
  nc_true?: number | null
  /** @nullable */
  overall_settings?: string | null
  round_precision: number
  scoring_algorithm: string
  stage_id: string
  /** @nullable */
  status_scores?: string | null
  /** @nullable */
  title?: string | null
}
