/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */

/**
 * Generic object.
 * @nullable
 */
export type RankingOverallSettings = {
  maxRacesCounted?: number
  minPointsAsOrg?: number
  organizerScoringFraction?: number
  totalCircuitRaces?: number
} | null
