/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.4
 */
import type { RawUploadFileData } from './rawUploadFileData'

/**
 * Entity RawUpload
 */
export interface RawUpload {
  id: string
  event_id: string
  stage_id: string
  upload_log_id: string
  /** Any object */
  file_data: RawUploadFileData
  created: string
  modified: string
  /** @nullable */
  deleted?: string | null
}
