/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { RawUploadFileData } from './rawUploadFileData'

/**
 * Entity RawUpload
 */
export interface RawUpload {
  created: string
  /** @nullable */
  deleted?: string | null
  event_id: string
  /** Any object */
  file_data: RawUploadFileData
  id: string
  modified: string
  stage_id: string
  upload_log_id: string
}
