/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.3
 */
import type { Event } from './event'

/**
 * Data wrapper for Event
 */
export interface ResEvent {
  data: Event
}
