/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { FedoStats } from './fedoStats'

/**
 * Data wrapper for FedoStats
 */
export interface ResFedoStats {
  data: FedoStats
}
