/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { PdfBook } from './pdfBook'

/**
 * Data wrapper for PdfBook
 */
export interface ResPdfBook {
  data: PdfBook
}
