/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { Ranking } from './ranking'

/**
 * Data wrapper for Ranking
 */
export interface ResRanking {
  data: Ranking
}
