/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { Result } from './result'

/**
 * Data wrapper for Result
 */
export interface ResResult {
  data: Result
}
