/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { RankingOrganizer } from './rankingOrganizer'

/**
 * Data wrapper for RankingOrganizer
 */
export interface ResRankingOrganizer {
  data: RankingOrganizer
}
