/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { StageOrder } from './stageOrder'

/**
 * Data wrapper for StageOrder
 */
export interface ResStageOrder {
  data: StageOrder
}
