/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.3
 */
import type { UploadedMeta } from './uploadedMeta'
import type { ResUploadedData } from './resUploadedData'

/**
 * Data wrapper for ResUploaded
 */
export interface ResUploaded {
  meta?: UploadedMeta
  /** Any object */
  data: ResUploadedData
}
