/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.4
 */
import type { User } from './user'

/**
 * Data wrapper for User
 */
export interface ResUser {
  data: User
}
