/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { UploadedMeta } from './uploadedMeta'
import type { ResUploadedData } from './resUploadedData'

/**
 * Data wrapper for ResUploaded
 */
export interface ResUploaded {
  meta?: UploadedMeta
  /** Any object */
  data: ResUploadedData
}
