/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { ClassEntity } from './classEntity'

/**
 * Entity RunnerSearch
 */
export interface RunnerSearch {
  /** @nullable */
  class?: ClassEntity
  first_name: string
  id: string
  last_name: string
}
