/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.3
 */

/**
 * Entity SimpleLog
 */
export interface SimpleLog {
  link_upload?: string
  upload_type?: string
  state?: number
  link_stage?: string
}
