/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */

/**
 * Entity SimpleLog
 */
export interface SimpleLog {
  link_stage?: string
  link_upload?: string
  state?: number
  upload_type?: string
}
