/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.3
 */
import type { Control } from './control'

/**
 * Entity Split
 */
export interface Split {
  id: string
  is_intermediate?: boolean
  reading_time?: string
  /** @nullable */
  points?: string | null
  /** @nullable */
  order_number?: string | null
  created?: string
  control?: Control
  station?: number
}
