/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { StageLinks } from './stageLinks'
import type { UploadLog } from './uploadLog'
import type { StageType } from './stageType'

/**
 * Entity Stage
 */
export interface Stage {
  _links: StageLinks
  description: string
  id: string
  last_logs: UploadLog[]
  stage_type?: StageType
  /** @nullable */
  start?: string | null
}
