/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.4
 */

/**
 * Entity StageOrder
 */
export interface StageOrder {
  id: string
  description: string
}
