/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { StageType } from './stageType'
import type { UploadLog } from './uploadLog'
import type { StageLinks } from './stageLinks'

/**
 * Entity Stage
 */
export interface Stage {
  id: string
  description: string
  /** @nullable */
  start?: string | null
  stage_type?: StageType
  last_logs: UploadLog[]
  _links: StageLinks
}
