/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { LinkHref } from './linkHref'

/**
 * Entity StageLinks
 */
export interface StageLinks {
  self?: LinkHref
  results?: LinkHref
  classes?: LinkHref
}
