/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.3
 */
import type { StageType } from './stageType'
import type { UploadLog } from './uploadLog'
import type { StageLinks } from './stageLinks'

/**
 * Entity Stage
 */
export interface Stage {
  id: string
  description: string
  stage_type: StageType
  last_logs: UploadLog[]
  _links: StageLinks
}
