/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */

/**
 * Entity StageOrderManagement
 */
export interface StageOrderManagement {
  created: string
  description: string
  id: string
  is_official: boolean
  original_event_id: string
  original_stage_id: string
  stage_order: number
  start: string
}
