/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.4
 */

/**
 * Entity Stats
 */
export interface Stats {
  classes?: string[]
  total?: number
  dns?: number
  mp?: number
  dnf?: number
  ot?: number
  dqf?: number
  notYetFinished?: number
  finished?: number
  others?: number
  otherValues?: string[]
}
