/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */

/**
 * Entity StatsInClass
 */
export interface StatsInClass {
  bestTime?: number
  class?: string
  dnf?: number
  dns?: number
  dsq?: number
  mp?: number
  ok?: number
  ot?: number
  total?: number
}
