/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */

/**
 * Entity Stats
 */
export interface Stats {
  classes?: string[]
  total?: number
  dns?: number
  mp?: number
  dnf?: number
  ot?: number
  dqf?: number
  notYetFinished?: number
  finished?: number
  others?: number
  otherValues?: string[]
}
