/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { UploadedV2MetaTimingsProcessingRunners } from './uploadedV2MetaTimingsProcessingRunners'

/**
 * objectInArray
 */
export type UploadedV2MetaTimingsProcessing = {
  courses?: number
  /** objectInArray */
  runners?: UploadedV2MetaTimingsProcessingRunners
  total?: number
}
