/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.3
 */

/**
 * Generic object.
 */
export type UploadDataTransferConfiguration = {
  source_vendor?: string
  source?: string
  source_version?: number
  contents?: string
  results_type?: string
  utf?: number
}
