/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.4
 */
import type { UploadedMetaUpdated } from './uploadedMetaUpdated'

/**
 * Entity UploadedMeta
 */
export interface UploadedMeta {
  /** Generic object. */
  updated?: UploadedMetaUpdated
  humanColor?: string
  human?: string[]
}
