/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { UploadDataTransferEventStagesItem } from './uploadDataTransferEventStagesItem'

/**
 * Generic object.
 */
export type UploadDataTransferEvent = {
  id?: string
  description?: string
  stages?: UploadDataTransferEventStagesItem[]
}
