/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { UploadedV2MetaTimingsProcessing } from './uploadedV2MetaTimingsProcessing'
import type { UploadedV2MetaTimingsSaving } from './uploadedV2MetaTimingsSaving'

/**
 * Generic object.
 */
export type UploadedV2MetaTimings = {
  /** objectInArray */
  processing?: UploadedV2MetaTimingsProcessing
  /** objectInArray */
  saving?: UploadedV2MetaTimingsSaving
  total?: number
}
