/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { UploadDataTransferConfiguration } from './uploadDataTransferConfiguration'
import type { UploadDataTransferEvent } from './uploadDataTransferEvent'

/**
 * Entity UploadDataTransfer
 */
export interface UploadDataTransfer {
  /** Generic object. */
  configuration?: UploadDataTransferConfiguration
  /** Generic object. */
  event?: UploadDataTransferEvent
}
