/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * O-replay - OpenAPI 3.0
 * O-replay Rest API
 * OpenAPI spec version: 0.4.3
 */

/**
 * Empty array
 */
export type UploadDataTransferEventStagesItem = { [key: string]: unknown }
