/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */
import type { UploadedMetaUpdated } from './uploadedMetaUpdated'

/**
 * Entity UploadedMeta
 */
export interface UploadedMeta {
  human?: string[]
  humanColor?: string
  /** Generic object. */
  updated?: UploadedMetaUpdated
}
