/**
 * Generated by orval. Do not edit manually.
 * O-replay - OpenAPI 3.0
 */

/**
 * Entity User
 */
export interface User {
  id: string
  email: string
  first_name: string
  last_name: string
  created?: string
  modified?: string
}
